### ISSUE TITLE
ENABLE THUMBNAILS IN 2.3.0

### ISSUE THREAD

**Issue by MrDragon420** [jneilliii/OctoPrint-PrusaSlicerThumbnails#67] opened 2021-02-25 13:26 UTC
There is not a checkbox anymore, what do i need to enter into it to make it work
![Screenshot 2021-02-25 052527](https://user-images.githubusercontent.com/78440986/109159821-edaf8680-7729-11eb-8bb4-d3aad58a1c54.png)

**Comment by jneilliii** [comment] 2021-02-25 15:13
Enter the following for the default that Prusa enabled on the Mini.

`16x16,220x124`

**Comment by jneilliii** [comment] 2021-02-25 15:14
duplicate of #58

**Closed by jneilliii** 2021-02-25 15:14 UTC
